stages:
  - test
  - build
  - deploy

test-backend:
  stage: test
  image: maven:3.8.5-openjdk-17
  variables:
    MAVEN_OPTS: "-Dspring.profiles.active=test"
  script:
    - echo "DB_URL=$DB_URL" > server/.env
    - echo "DB_USERNAME=$DB_USERNAME" >> server/.env
    - echo "DB_PASSWORD=$DB_PASSWORD" >> server/.env
    - echo "JWT_SECRET=$JWT_SECRET" >> server/.env
    - echo "JWT_EXPIRATION=$JWT_EXPIRATION" >> server/.env
    - cd server
    - mvn clean test

test-frontend:
  stage: test
  image: node:18
  script:
    - cd client
    - npm install
    - npm run test

build-backend:
  stage: build
  image: docker:20.10.16
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd server
    - mvn clean package -DskipTests
    - docker build -t $CI_REGISTRY_IMAGE/backend:latest .
    - docker push $CI_REGISTRY_IMAGE/backend:latest
  artifacts:
    paths:
      - server/target/*.jar
  dependencies:
    - test-backend

build-frontend:
  stage: build
  image: docker:20.10.16
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd client
    - npm install
    - npm run build
    - docker build -t $CI_REGISTRY_IMAGE/frontend:latest .
    - docker push $CI_REGISTRY_IMAGE/frontend:latest
  artifacts:
    paths:
      - client/dist
  dependencies:
    - test-frontend

deploy:
  stage: deploy
  image: docker/compose:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - echo "DB_URL=$DB_URL" > .env
    - echo "DB_USERNAME=$DB_USERNAME" >> .env
    - echo "DB_PASSWORD=$DB_PASSWORD" >> .env
    - echo "JWT_SECRET=$JWT_SECRET" >> .env
    - echo "JWT_EXPIRATION=$JWT_EXPIRATION" >> .env
  script:
    - docker-compose down --remove-orphans
    - docker-compose pull  # Récupère les images depuis le registre GitLab
    - docker-compose up -d
    - docker ps -a
  only:
    - main

