stages:
  - test
  - build
  - deploy

# --- TEST BACKEND ---

test-backend:
  stage: test
  image: maven:3.8.5-openjdk-17
  # Ici, on indique explicitement d'utiliser le profil "test" et on injecte JWT_SECRET/EXPIRATION
  variables:
    MAVEN_OPTS: "-Dspring.profiles.active=test -DJWT_SECRET=$JWT_SECRET -DJWT_EXPIRATION=$JWT_EXPIRATION"
  script:
    - cd server
    - mvn clean test

# --- TEST FRONTEND ---

test-frontend:
  stage: test
  image: node:16
  script:
    - cd client
    - npm install
    - npm run test

# --- BUILD BACKEND ---

build-backend:
  stage: build
  image: maven:3.8.5-openjdk-17
  # Ici, on injecte les variables de prod (MySQL), plus JWT si nécessaire
  variables:
    MAVEN_OPTS: "-Dspring.datasource.url=$DB_URL -Dspring.datasource.username=$DB_USERNAME -Dspring.datasource.password=$DB_PASSWORD -Djwt.secret=$JWT_SECRET -Djwt.expiration=$JWT_EXPIRATION"
  script:
    - cd server
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - server/target/*.jar
    # Facultatif, vous pouvez définir une durée de conservation des artefacts
    # expire_in: 1 week
  # Pour s'assurer que les tests sont passés avant de builder
  dependencies:
    - test-backend

# --- BUILD FRONTEND ---

build-frontend:
  stage: build
  image: node:16
  variables:
    VITE_API_URL: $VITE_API_URL
  script:
    - cd client
    - npm install
    - npm run build
  artifacts:
    paths:
      - client/dist
    # Facultatif : durée de conservation
    # expire_in: 1 week
  # Pour s'assurer que les tests front sont passés avant de builder
  dependencies:
    - test-frontend

# --- DEPLOY ---

deploy:
  stage: deploy
  script:
    - docker-compose down
    - docker-compose up -d
  only:
    - main
