version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "8081:8080"
    networks:
      - app-network
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      
  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge