version: '3.8'

services:
  server:
    image: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHA
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    depends_on:
      - client

  client:
    image: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHA
    ports:
      - "3000:80"
    networks:
      - app-network
    environment:
      VITE_API_URL: ${VITE_API_URL}

networks:
  app-network:
    driver: bridge
