# Définir la version de Docker Compose
version: '3.8'

# Définir les services
services:

  server:
    build:
      # Définir le contexte du Dockerfile
      context: ./server
    ports:
      - "8080:8080"
      # Définir le réseau permettant la communication entre les services
    networks:
      - app-network
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    depends_on:
      - client

  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    networks:
      - app-network
    environment:
      VITE_API_URL: ${VITE_API_URL}

networks:
  app-network:
    driver: bridge
