version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "8081:8080"
    networks:
      - app-network

  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge